In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
#from sklearn.externals import joblib
from sklearn import svm
from sklearn.preprocessing import StandardScaler
import os
from sklearn.model_selection import cross_val_score

In [2]:
df1=pd.read_csv("./processed/training/engaged.csv")
df2=pd.read_csv("./processed/training/notEngaged.csv")
dff=pd.read_csv("./TopFeatures.csv")

In [3]:
dft=pd.concat([df1,df2])

In [4]:
feat=dff.to_numpy()
feat=feat.reshape(-1)

In [5]:
y_train=dft["Result"]
x_train=dft.drop("Result",axis=1)
x_train=x_train[feat]

In [6]:
scaler = StandardScaler()
model = scaler.fit(x_train)
x_train = model.transform(x_train)

In [7]:
model_linear = svm.SVC(kernel = 'linear')
model_linear.fit(x_train, y_train)

model_poly = svm.SVC(kernel = 'poly')
model_poly.fit(x_train, y_train)

model_rbf = svm.SVC(kernel = 'rbf')
model_rbf.fit(x_train, y_train)

SVC()

In [8]:
patho=r'./models'
joblib.dump(model_linear, (os.path.join(patho,r''+'model_joblib_svm_linear')))
joblib.dump(model_poly, (os.path.join(patho,r''+'model_joblib_svm_poly')))
joblib.dump(model_rbf, (os.path.join(patho,r''+'model_joblib_svm_rbf')))

['./models/model_joblib_svm_rbf']

In [9]:
mj = joblib.load('./models/model_joblib_svm_linear')

mj1 = joblib.load('./models/model_joblib_svm_poly')

mj2 = joblib.load('./models/model_joblib_svm_rbf')

In [10]:
avg_score_mj=cross_val_score(mj,x_train, y_train, cv=5)

In [ ]:
avg_score_mj1=cross_val_score(mj,x_train, y_train, cv=5)

In [ ]:
avg_score_mj2=cross_val_score(mj,x_train, y_train, cv=5)

In [12]:
print(avg_score_mj)
print(sum(avg_score_mj)/5)

[0.69689413 0.60122421 0.61686692 0.78281569 0.77601451]
0.6947630922693266


In [13]:
print(avg_score_mj1)
print(sum(avg_score_mj1)/5)

[0.69689413 0.60122421 0.61686692 0.78281569 0.77601451]
0.6947630922693266


In [14]:
print(avg_score_mj2)
print(sum(avg_score_mj2)/5)

[0.69689413 0.60122421 0.61686692 0.78281569 0.77601451]
0.6947630922693266
